version: '3.8'

services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
#    depends_on:
#      - db-service
#
#  db-service:
#    build:
#      context: .
#      dockerfile: ../db/Dockerfile
##    ports:
##      - "5432:5432"