version: '3.8'

services:
  frontend:
    working_dir: /src
    image: hai0421/spring_cooler_front:latest
    ports:
      - 3000:3000
    environment:
      - HOST=0.0.0.0
    depends_on:
      - api-service
    restart: always
  api-service:
    image: hai0421/spring_cooler_back:latest
    ports:
      - 8080:8080